# Generated by Django 3.2.9 on 2021-11-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Postagens'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
    ]
