# Generated by Django 3.2.9 on 2021-11-23 04:10

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='media', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='media', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='post',
            name='criado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='media', verbose_name='Imagem'),
        ),
    ]
