# Generated by Django 3.2.9 on 2021-11-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='linkedin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
