# Generated by Django 3.2.9 on 2021-11-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_auto_20211102_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='nome',
            new_name='link',
        ),
    ]
