# Generated by Django 3.2.9 on 2021-11-03 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_rename_nome_social_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='link',
            new_name='nome',
        ),
    ]
