# Generated by Django 3.2.9 on 2021-11-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_rename_nome_social_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='link',
        ),
        migrations.AddField(
            model_name='social',
            name='stfacebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='social',
            name='stlinkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='social',
            name='sttwitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='social',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
