# Generated by Django 3.2.8 on 2021-11-03 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_auto_20211102_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='stfacebook',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='social',
            name='stlinkedin',
        ),
        migrations.RemoveField(
            model_name='social',
            name='sttwitter',
        ),
    ]
