# Generated by Django 3.2.8 on 2021-11-03 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0010_auto_20211102_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagina',
            old_name='endereco',
            new_name='cabecalho1',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='nome',
            new_name='cabecalho2',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='sobrenome',
            new_name='titulo',
        ),
    ]
