# Generated by Django 3.2.8 on 2021-11-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0011_auto_20211102_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagina',
            old_name='cabecalho1',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='cabecalho2',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='titulo',
            new_name='sobrenome',
        ),
    ]
