# Generated by Django 3.2.8 on 2021-11-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0013_cores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cores',
            name='cor',
            field=models.CharField(max_length=255),
        ),
    ]
