# Generated by Django 3.2.8 on 2021-11-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0014_alter_cores_cor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ('-atualizado',), 'verbose_name_plural': 'Redes Sociais'},
        ),
        migrations.AddField(
            model_name='social',
            name='atualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
