# Generated by Django 3.2.8 on 2021-11-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0015_auto_20211103_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cores',
            options={'ordering': ('-atualizado',), 'verbose_name_plural': 'Cores'},
        ),
        migrations.AddField(
            model_name='cores',
            name='atualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
